version: "3.9"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  minio-setup:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
      MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET:-datalake}
      MINIO_SVC_ACCESS_KEY: ${MINIO_SVC_ACCESS_KEY:-svcminio}
      MINIO_SVC_SECRET_KEY: ${MINIO_SVC_SECRET_KEY:-svcminio123}
      MINIO_SVC_POLICY_NAME: ${MINIO_SVC_POLICY_NAME:-svc-policy}
    volumes:
      - ./policies:/bootstrap/policies:ro
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} &&
        mc mb --ignore-existing local/$${MINIO_DEFAULT_BUCKET} &&
        mc admin policy create local $${MINIO_SVC_POLICY_NAME} /bootstrap/policies/$${MINIO_SVC_POLICY_NAME}.json 2>/dev/null || true &&
        mc admin service-account add local
          --access-key $${MINIO_SVC_ACCESS_KEY}
          --secret-key $${MINIO_SVC_SECRET_KEY}
          --policy $${MINIO_SVC_POLICY_NAME}
          --description 'Service account bootstrap' || true
      "
    restart: "no"
